version: "3.7"
services:
    powerdns41:
        image: psitrax/powerdns:4.1
        container_name: pdns41
        environment:
            MYSQL_USER: root
            MYSQL_PASS: verySecretPassword
            MYSQL_HOST: db-pdns41
        depends_on:
            - db-pdns41
        ports:
            - 8041:8081
        volumes:
            - ./.docker/powerdns:/etc/pdns/conf.d

    db-pdns41:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: verySecretPassword

    powerdns42:
        image: psitrax/powerdns:v4.2
        container_name: pdns42
        environment:
            MYSQL_USER: root
            MYSQL_PASS: verySecretPassword
            MYSQL_HOST: db-pdns42
        depends_on:
            - db-pdns42
        ports:
            - 8042:8081
        volumes:
            - ./.docker/powerdns:/etc/pdns/conf.d

    db-pdns42:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: verySecretPassword

    powerdns43:
        image: psitrax/powerdns:v4.3
        container_name: pdns43
        environment:
            MYSQL_USER: root
            MYSQL_PASS: verySecretPassword
            MYSQL_HOST: db-pdns43
        depends_on:
            - db-pdns43
        ports:
            - 8043:8081
        volumes:
            - ./.docker/powerdns:/etc/pdns/conf.d

    db-pdns43:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: verySecretPassword
